name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup with pkgx
        uses: pkgxdev/setup@v4
        with:
          +: astral.sh/uv
            astral.sh/ruff
            astral.sh/ty
            pytest.org

      - name: Lock the dependencies
        run: pkgx uv lock

      - name: Install the project
        run: pkgx uv sync --locked --all-extras --dev

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: ./src
      # TODO: ty is in beta rn. so this is experimental
      - name: Type check with ty
        run: |
          pkgx ty check src/ tests/
      - name: Run tests with pytest
        run: |
          pkgx pytest tests
